config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login',    to: 'devise/sessions#new', as: :login
    get '/logout',   to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get     "/login"  => "devise/sessions#new", as: :new_user_session
    post    "/login"  => "devise/sessions#create", as: :user_session
    delete  "/logout" => "devise/sessions#destroy", as: :destroy_user_session
  end

  resources :statuses do
    resources :comments
  end
  resources :comments

  resource :user_friendships

  get 'feed', to: "statuses#index", as: :feed
  root "statuses#index"

  get '/:id', to: "profiles#show", as: :profile

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :status
  belongs_to :user
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  has_many  :comments

  default_scope -> { order(created_at: :DESC)}

  validates :content, presence: true,
            length: {minimum: 2}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  has_many :comments
  has_many :statuses
  has_many :user_friendships

  has_many :friends, -> { where(user_friendships: { state: "accepted"}) }, through: :user_friendships
  # has_many :pending_user_friendships, -> { where(user_friendships: { state: "pending" }) }, class_name: 'UserFriendship', foreign_key: :user_id
  has_many :pending_friends, -> { where user_friendships: { state: "pending" } }, through: :user_friendships, source: :friend




  validates :first_name,    presence: true
  validates :last_name,     presence: true

  validates :profile_name,  presence: true,
                            uniqueness: true,
                            format: {
                                    with: /\A[a-zA-Z0-9_-]+\z/,

                                    message: "Must be formatted correctly." }

  def to_param
    profile_name
  end

  def full_name
    first_name + " " + last_name
  end

  def gravatar_url
    stripped_email =  email.strip
  end
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: "friend_id"

  state_machine :state, initial: :pending do
    after_transition on: :accept, do: :send_acceptance_email

    state :requested

    event :accept do
      transition any => :accepted
    end
  end

  def self.request(user1,user2)
    transaction do
      friendship1 = create!(user: user1, friend: user2, state: "pending")
      friendship2 = create!(user: user2, friend: user1, state: "requested")

      friendship1.send_request_email
      friendship1
    end
  end

  def send_request_email
    UserNotifier.friend_requested(id).deliver_now
  end

  def send_acceptance_email
     UserNotifier.friend_request_accepted(id).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :profile_name, :email, :password,
      :password_confirmation, :remember_me, :avatar, :avatar_cache) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :profile_name, :email, :password,
      :password_confirmation, :remember_me, :avatar, :avatar_cache)  }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
      @status = Status.find_by(params[:status_id])
      @comment = @status.comments.create(params_comment)
      @comment.save
      redirect_to statuses_path
    end

    def index
     @statuses = Status.all
     @comments = Comment.all
     @comment = Comment.find_by(params[:id])
    end


    def new
      @status  = Status.find(params[:status_id])
      @comment = Comment.new

    end
   private

   def params_comment
     params.require(:comment).permit(:content)
   end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file:'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    @statuses = Status.all
    @comments = Comment.all
  end

  def show
    @status = Status.find(params[:id])
    @comments = @status.comments.all
  end

  def new
    @status = Status.new
    @comment = @status.comments.build
  end

  def create
    # @status = Status.new(status_params)
    # @status.user = current_user
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @status = current_user.statuses.find(params[:id])
    if params[:status] && params[:status].has_key?(:user_id)
       params[:status].delete(:user_id)
    end
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_status
      @status = Status.find(params[:id])
    end

    def status_params
      params.require(:status).permit(:user_id, :content)
    end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
  before_filter :authenticate_user!, only: [:new]


  def new
    if params[:friend_id]
      @friend = User.where(profile_name: params[:friend_id]).first
      raise ActiveRecord::RecordNotFound if @friend.nil?
      @user_friendship = current_user.user_friendships.new(friend: @friend)
    else
      flash[:error] ="Friend requiered"
    end
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404', status: :not_found
  end

 def create
   if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
     @friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
     @user_friendship = current_user.user_friendships.new(friend: @friend)
     @user_friendship.save
     flash[:success] = "You are now friend with #{@friend.full_name}"
     redirect_to profile_path(@friend)
   else
     flash[:error] = "Friend requiered"
     redirect_to root_path
   end
 end


  private
  def user_friendship_params
    params.require(:friendship).permit(:user, :friend, :user_id, :friend_id, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
    case type
    when 'alert'
      "alert-danger"
    when 'notice'
      "alert-success"
    else
      " "
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for status.comments.new do |f|%>
 <%= f.input :content %>
 <%= f.button :submit %>
<% end  %>

<!-- I still have to find out what is wrong in this form.... -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div>
        <a class="navbar-brand" href="#">
        TreeBook
        </a>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "All Statuses", feed_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.full_name, edit_user_registration_path%></li>
            <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Register", register_path %></li>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
</nav>
<body>


 <div class="container">

   <% flash.each do |type, message| %>
       <div class="alert <%= flash_class(type.to_s) %>">
           <button class="close" data-dismiss="alert">x</button>
           <%= message %>
       </div>
   <% end %>




   <%= yield %>
 </div>


</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name%></h1>
  <%= link_to "Add Friend", new_user_friendships_path(friend_id: @user), class:"btn btn-primary"%>
</div>

<% if @statuses %>
  <% @statuses.each do |status| %>
  <div class="well">
    <%= image_tag status.user.avatar.thumb if status.user.avatar?%>
    <%= status.content %>
    <hr>
    <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
  </div>
  <% end %>
<%end %>

app/views/shared/_users_list.html.erb
<div class="user-side">
  <div class="col-xs-3">
    <div class="page-header">
      <h2>All Users</h2>
    </div>
    <% @users.each do |user| %>
    <li><h5>
       <%= user.full_name %>
    </h5></li>
    <% end %>
  </div>
</div>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-xs-12 col-sm-offset-2 col-sm-8">
    <!-- <%= f.input :user_id , collection: User.all, label_method: :full_name%> -->
    <%= f.input :content %>
    <%= f.button :submit %>
</div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="row whole-page">
  <div class="row">
    <div class="page-header">
    <h1>Hey, welcome on TreeBook</h1>
    </div>
  </div>
  <div class="col-xs-9">
    <div class="page-header">
        <h2>All of the Statuses</h2>
    </div>
    <%= link_to "Post A New Status", new_status_path, class: "btn btn-success"%>
    <br>
    <br>
      <% @statuses.each do |status| %>
          <div class="status">

          <div class="row">
            <div class="col-xs-1 avatar">
              <%= link_to image_tag(status.user.avatar.thumb), profile_path(status.user) if status.user.avatar? %>
            </div>
            <div class="col-xs-7 user-name">
              <h4><%= status.user.full_name%></h4>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-8">
             <p><%= simple_format(status.content) %></p>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-8">
              <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
              <% if status.user == current_user %>
                <span class="admin">
                |  <%= link_to "Edit", edit_status_path(status) %> |
                   <%= link_to "Delete", status, method: :delete, data: {confirm: "Are you sure?"} %>
                </span>
              <% end  %>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12">
              <% status.comments.each do |comment| %>
                <li class="comment-box">
                  <%= comment.content %>
                </li><br>

              <% end %>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12">
                <%= render partial: "comments/form", locals: {status: status} %>
            </div>
          </div>
        </div>
      <% end %>


  </div>
  <div class="user-side">
    <div class="col-xs-3">
      <div class="page-header">
        <h2>All Users</h2>
      </div>
      <% @users.each do |user| %>
      <li><h5>
         <%= user.full_name %>
      </h5></li>
      <% end %>
    </div>
  </div>
  </div>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/user_friendships/create.html.erb
PLOC

app/views/user_friendships/new.html.erb
<% if @friend %>
  <h1><%= @friend.full_name %></h1>
  <p>Do you really want to friend <%= @friend.full_name %>?</p>


  <%= form_for @user_friendship, method: :post do |f| %>
    <div class="form form-actions">
      <%= f.hidden_field :friend_id, value: @friend.profile_name%>
      <%= submit_tag "Yes, add friend", class:"btn btn-primary" %>
      <%= link_to "Cancel", profile_path(@friend), class:"btn" %>
    </div>

  <% end %>

<% end %>

app/views/user_notifier/friend_request_accepted.html.erb
Hi <%= @friend.first_name %>,

<%= @user.first_name %> has accepted your friend request !!!
Love,

Mike The Frog

app/views/user_notifier/friend_requested.html.erb
Hi <%= @friend.first_name %>,

<%= @user.first_name %> wants to be friends on Treebook, isn't that great?

Love,

Mike The Frog